@URL = http://localhost:8000
### get all customers
GET {{URL}}/api/customers

### get single customers
GET {{URL}}/api/customers/2

### get id out of range
GET {{URL}}/api/customers/100
### get invalid id
GET {{URL}}/api/customers/asdf
### create customer
POST {{URL}}/api/customers
Content-Type: application/json

{
    "id":2,
    "firstname":"Joe",
    "lastname":"Mama"
}

### delete customer
DELETE {{URL}}/api/customers/1
